server:
  port: 3223

spring:
  datasource:
    url: jdbc:h2:file:./blog_app;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create # in prod, use update, NOT create